private _crate = acces;
clearMagazineCargoGlobal _crate;
clearWeaponCargoGlobal _crate;
clearItemCargoGlobal _crate;
clearBackpackCargoGlobal _crate;

_crate addItemCargoGlobal ["R3F_SILENCIEUX_HK416", 50];
_crate addItemCargoGlobal ["ACE_CableTie", 50];
_crate addItemCargoGlobal ["ACE_Chemlight_HiGreen", 50];
_crate addItemCargoGlobal ["ACE_DefusalKit", 10]; 
_crate addItemCargoGlobal ["ACE_EntrenchingTool", 10];
_crate addItemCargoGlobal ["R3F_FUM40", 50];
_crate addItemCargoGlobal ["B_IR_Grenade", 50];
_crate addItemCargoGlobal ["R3F_POINTEUR_SURB", 10];
_crate addItemCargoGlobal ["DemoCharge_Remote_Mag", 50];
_crate addItemCargoGlobal ["ACE_MapTools", 10];
_crate addItemCargoGlobal ["ACE_wirecutter", 10];
_crate addItemCargoGlobal ["ACE_Kestrel4500", 5];
_crate addItemCargoGlobal ["R3F_OB50", 10];
_crate addItemCargoGlobal ["ACE_NVG_Wide", 25];
_crate addItemCargoGlobal ["B_UavTerminal", 5];
_crate addItemCargoGlobal ["ClaymoreDirectionalMine_Remote_Mag", 50];
_crate addItemCargoGlobal ["SatchelCharge_Remote_Mag", 50];
_crate addItemCargoGlobal ["ACE_UAVBattery", 50];
_crate addItemCargoGlobal ["R3F_LAMPE_SURB", 50];
_crate addItemCargoGlobal ["muzzle_snds_L", 50]; //sds 9mm
_crate addItemCargoGlobal ["ACE_M26_Clacker", 10];
_crate addItemCargoGlobal ["ACE_Clacker", 10];
_crate addItemCargoGlobal ["ACE_Tripod", 5];
_crate addItemCargoGlobal ["ACE_Vector", 5];
_crate addItemCargoGlobal ["Laserbatteries", 5];
_crate addItemCargoGlobal ["tfw_rf3080Item", 5];
_crate addItemCargoGlobal ["tfw_ilbe_whip_gr", 5];
//_crate addItemCargoGlobal ["tfw_ilbe_whip_ocp", 5];
