/*
* Auteur : Wolv
* Ajoute les loads par default a l'arsenal ACE.
*
* Arguments :
*
* Exemple:
* [] call DISLoad_fnc_Varload;
*
* Variable publique :
* - DISLoad_var_piloteAvions
* - DISLoad_var_piloteHelo
* - DISLoadMc_var_CDBR
* - DISLoadMc_var_CDB
* - DISLoadMc_var_CdE
* - DISLoadMc_var_CdG
* - DISLoadMc_var_CdS
* - DISLoadMc_var_EOD
* - DISLoadMc_var_EOD_Light
* - DISLoadMc_var_Equipier
* - DISLoadMc_var_Grenadier
* - DISLoadMc_var_GV
* - DISLoadMc_var_GvBck
* - DISLoadMc_var_Medecin
* - DISLoadMc_var_Minimi5
* - DISLoadMc_var_Minimi7
* - DISLoadMc_var_TP
* - DISLoadMc_var_Zeus
* - DISLoadPL_var_CDE
* - DISLoadPL_var_CDG
* - DISLoadPL_var_GV
* - DISLoadPL_var_Medecin
* - DISLoadPL_var_Minimi5
*/

DISLoad_var_piloteAvions = [[[],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_PilotCoveralls",[["ACE_morphine",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_elasticBandage",5],["ACE_splint",3],["ACE_EarPlugs",1],["ACE_CableTie",1],["ACE_packingBandage",5],["rhsusf_mag_17Rnd_9x19_JHP",3,17],["SmokeShell",2,1],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1]]],[],["B_Parachute",[]],"H_PilotHelmetFighter_B","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoad_var_piloteHelo = [[["rhsusf_weap_MP7A2","","","rhsusf_acc_eotech_xps3",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",1],["ACE_tourniquet",4],["ACE_elasticBandage",20],["ACE_epinephrine",3],["ACE_packingBandage",20],["ACE_morphine",5],["ACE_CableTie",1]]],["V_PlateCarrier2_blk",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhsusf_mag_40Rnd_46x30_FMJ",3,40],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1],["SmokeShell",4,1],["ACE_Chemlight_HiGreen",1,1]]],[],"rhsusf_ihadss","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];

DISLoadMc_var_CDBR = [[["rhs_weap_hk416d10","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_light",[["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ToolKit",1],["ACE_plasmaIV_500",4]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]],[["ace_earplugs",true]]];
DISLoadMc_var_CDB = [[["rhs_weap_hk416d10","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_light",[["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ToolKit",1],["ACE_plasmaIV_500",4]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]],[["ace_earplugs",true]]];
DISLoadMc_var_CdE = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1]]],"rhsusf_opscore_mc_cover_pelt","",["Binocular","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_CdG = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1]]],"rhsusf_opscore_mc_cover_pelt","",["Laserdesignator","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_CdS = [[["rhs_weap_hk416d10","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["TFAR_rt1523g_rhs",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1]]],"rhsusf_opscore_mc_cover_pelt_cam","",["Laserdesignator","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_EOD = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_spc_iar",[["ACE_plasmaIV_500",4],["ACE_DefusalKit",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",5,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["R3F_ITEM_Brouilleur",1],["SmokeShell",5,1],["rhsusf_m112_mag",2,1],[["ACE_VMM3","","","",[],[],""],1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_EOD_Light = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_spc_iar",[["ACE_DefusalKit",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",5,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["R3F_ITEM_Brouilleur",1],["SmokeShell",5,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Equipier = [[["rhs_weap_hk416d10","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_light",[["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ToolKit",1],["ACE_plasmaIV_500",4]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Grenadier = [[["rhs_weap_hk416d145_m320","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_grenadier",[["30Rnd_556x45_Stanag_red",10,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["rhs_mag_M433_HEDP",15,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_GV = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],[],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_rifleman",[["ACE_plasmaIV_500",2],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1]]],[],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_GvBck = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_rifleman",[["30Rnd_556x45_Stanag_red",10,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Medecin = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_teamleader",[["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m18_green",1,1],["rhs_mag_m18_purple",1,1],["rhsusf_mag_17Rnd_9x19_JHP",1,17]]],["B_Kitbag_mcamo",[["ACE_tourniquet",2],["ACE_splint",10],["ACE_epinephrine",8],["ACE_morphine",8],["ACE_bloodIV",8],["ACE_bloodIV_500",12],["ACE_elasticBandage",20],["ACE_packingBandage",30],["ACE_surgicalKit",1]]],"rhsusf_opscore_paint","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Minimi5 = [[["rhs_weap_m249_light_S","","","rhsusf_acc_eotech_xps3",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_machinegunner",[["rhsusf_200Rnd_556x45_box",3,200]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["rhs_mag_m67",2,1],["SmokeShell",5,1],["rhsusf_200Rnd_556x45_box",1,200]]],"rhsusf_opscore_mc_cover","",["Laserdesignator","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Minimi7 = [[["rhs_weap_m240G","","","rhsusf_acc_ELCAN",["rhsusf_100Rnd_762x51",100],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_machinegunner",[["rhsusf_100Rnd_762x51",4,100]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",2],["rhs_mag_m67",2,1],["SmokeShell",5,1],["rhsusf_200Rnd_556x45_box",2,200]]],"rhsusf_opscore_mc_cover","",["Laserdesignator","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_TP = [[["rhs_weap_mk17_LB","","","rhsusf_acc_su230a_c",["rhs_mag_20Rnd_SCAR_762x51_m80_ball",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",5],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_marksman",[["rhs_mag_20Rnd_SCAR_762x51_m80_ball",8,20],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["SmokeShell",10,1],["rhs_mag_m67",2,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_Zeus = [[["rhs_weap_hk416d10","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_CombatUniform_mcam_tshirt",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["V_Rangemaster_belt",[["30Rnd_556x45_Stanag_red",5,30]]],["TFAR_rt1523g_green",[]],"H_MilCap_mcamo","",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];

DISLoadPL_var_CDE = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_CableTie",4],["ACE_elasticBandage",10],["ACE_morphine",5],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["ACE_EarPlugs",1],["R3F_ITEM_ODP",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["V_RebreatherB",[]],["rhssaf_kitbag_smb",[["ACE_plasmaIV_500",4],["SmokeShellGreen",1,1],["30Rnd_556x45_Stanag_red",10,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["rhsusf_plateframe_light",false]]],"rhsusf_opscore_mc","G_B_Diving",["Binocular","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadPL_var_CDG = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_CableTie",4],["ACE_elasticBandage",10],["ACE_morphine",5],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["ACE_EarPlugs",1],["R3F_ITEM_ODP",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["V_RebreatherB",[]],["rhssaf_kitbag_smb",[["ACE_plasmaIV_500",4],["SmokeShellGreen",1,1],["30Rnd_556x45_Stanag_red",10,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["rhsusf_plateframe_light",false]]],"rhsusf_opscore_mc","G_B_Diving",["Binocular","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadPL_var_GV = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_CableTie",4],["ACE_elasticBandage",10],["ACE_morphine",5],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["ACE_EarPlugs",1],["R3F_ITEM_ODP",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["V_RebreatherB",[]],["rhssaf_kitbag_smb",[["ACE_plasmaIV_500",4],["SmokeShellGreen",1,1],["30Rnd_556x45_Stanag_red",10,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["rhsusf_plateframe_light",false]]],"rhsusf_opscore_mc","G_B_Diving",["Binocular","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadPL_var_Medecin = [[["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_elasticBandage",20],["ACE_morphine",5],["ACE_EarPlugs",1],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["rhsusf_mag_17Rnd_9x19_JHP",1,17],["SmokeShell",3,1]]],["V_RebreatherB",[]],["rhssaf_kitbag_smb",[["ACE_bloodIV",10],["ACE_bloodIV_500",5],["ACE_surgicalKit",1],["30Rnd_556x45_Stanag_red",6,30],["rhsusf_plateframe_light",false]]],"rhsusf_opscore_paint","G_B_Diving",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadPL_var_Minimi5 = [[["rhs_weap_m249_light_S","","","rhsusf_acc_eotech_xps3",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_CableTie",4],["ACE_elasticBandage",10],["ACE_morphine",5],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["ACE_EarPlugs",1],["rhsusf_mag_17Rnd_9x19_JHP",3,17],["SmokeShell",4,1]]],["V_RebreatherB",[]],["rhssaf_kitbag_smb",[["ACE_plasmaIV_500",4],["rhs_mag_m67",2,1],["rhsusf_200Rnd_556x45_box",3,200],["rhsusf_plateframe_light",false]]],"rhsusf_opscore_mc","G_B_Diving",[],["ItemMap","","TFAR_anprc152","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];



