/*
* Auteur : Wolv
* Ajoute les loads par default a l'arsenal ACE.
*
* Arguments :
*
* Exemple:
* [] call DISLoad_fnc_Varload;
*
* Variable publique :
* - DISLoad_var_piloteAvions
* - DISLoad_var_piloteHelo
* - DISLoadMc_var_CDBR
* - DISLoadMc_var_CDB
* - DISLoadMc_var_CdE
* - DISLoadMc_var_CdG
* - DISLoadMc_var_CdS
* - DISLoadMc_var_EOD
* - DISLoadMc_var_EOD_Light
* - DISLoadMc_var_Equipier
* - DISLoadMc_var_Grenadier
* - DISLoadMc_var_GV
* - DISLoadMc_var_GvBck
* - DISLoadMc_var_Medecin
* - DISLoadMc_var_Minimi5
* - DISLoadMc_var_Minimi7
* - DISLoadMc_var_TP
* - DISLoadMc_var_Zeus
* - DISLoadPL_var_CDE
* - DISLoadPL_var_CDG
* - DISLoadPL_var_GV
* - DISLoadPL_var_Medecin
* - DISLoadPL_var_Minimi5
*/

DISLoad_var_piloteHelo = [[["rhsusf_weap_MP7A2","","","rhsusf_acc_g33_xps3",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_m81",[["ACE_EarPlugs",1],["ACE_tourniquet",4],["ACE_elasticBandage",20],["ACE_epinephrine",3],["ACE_packingBandage",20],["ACE_morphine",3],["ACE_CableTie",1],["ACE_painkillers",1,10]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhsusf_mag_40Rnd_46x30_FMJ",3,40],["SmokeShell",5,1],["ACE_Chemlight_HiGreen",1,1],["acex_intelitems_notepad",1,1]]],[],"rhsusf_hgu56p_black","",[],["ItemMap","ItemGPS","TFAR_anprc152_2","ItemCompass","ItemWatch","ACE_NVG_Wide_Black_WP"]],[["ace_earplugs",true]]];
DISLoad_var_piloteAvions = [[[],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_PilotCoveralls",[["ACE_morphine",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_elasticBandage",5],["ACE_splint",2],["ACE_EarPlugs",1],["ACE_packingBandage",5],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_JHP",3,17],["SmokeShellBlue",1,1],["SmokeShellGreen",1,1],["SmokeShell",2,1],["acex_intelitems_notepad",1,1]]],[],["B_Parachute",[]],"H_PilotHelmetFighter_B","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_30","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 

DISLoadMc_var_CDBR = [[["rhs_weap_hk416d10","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_light",[["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["acex_intelitems_notepad",1,1]]],["rhsusf_falconii_mc",[["ToolKit",1],["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_28","ItemCompass","ItemWatch","ACE_NVG_Wide"]],[["ace_earplugs",true]]]; 
DISLoadMc_var_CDB = [[["rhs_weap_hk416d10","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_light",[["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_elasticBandage",10],["ACE_packingBandage",15],["ACE_surgicalKit",1],["ACE_bloodIV",6],["ACE_bloodIV_500",10]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_29","ItemCompass","ItemWatch","ACE_NVG_Wide"]],[["ace_earplugs",true]]]; 
DISLoadMc_var_CdE = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1],["ACE_elasticBandage",10],["ACE_packingBandage",15],["ACE_painkillers",1,10]]],"rhsusf_opscore_mc_cover_pelt","",["Binocular","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_15","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_CdG = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["ACE_EarPlugs",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1],["ACE_elasticBandage",10],["ACE_packingBandage",15]]],"rhsusf_opscore_mc_cover_pelt","",["Laserdesignator","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_17","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_CdGM = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["ACE_EarPlugs",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["B_Kitbag_mcamo",[["ACE_tourniquet",2],["ACE_splint",6],["ACE_epinephrine",5],["ACE_morphine",5],["ACE_bloodIV",8],["ACE_bloodIV_500",12],["ACE_elasticBandage",15],["ACE_packingBandage",20],["ACE_surgicalKit",1]]],"rhsusf_opscore_mc_cover_pelt","",["Laserdesignator","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_19","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];
DISLoadMc_var_CdS = [[["rhs_weap_hk416d10","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],["rhs_weap_M136","","","",[],[],""],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["ACE_EarPlugs",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["tfw_ilbe_whip_mc",[["ACE_plasmaIV_500",4],["ACE_packingBandage",15],["ACE_elasticBandage",10]]],"rhsusf_opscore_mc_cover_pelt_cam","",["Laserdesignator","","","",[],[],""],["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152_20","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_EOD = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["ACE_VMM3","","","",[],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_spc_iar",[["ACE_DefusalKit",1],["ACE_EarPlugs",1],["ACE_Clacker",1],["ACE_elasticBandage",10],["ACE_packingBandage",15],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",5,1],["rhs_mag_m67",3,1]]],["rhsusf_falconii_mc",[["R3F_ITEM_Brouilleur",1],["ACE_plasmaIV_500",4],["rhsusf_m112_mag",4,1],["DemoCharge_Remote_Mag",2,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_23","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_EOD_Light = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_spc_iar",[["ACE_DefusalKit",1],["ACE_EarPlugs",1],["ACE_elasticBandage",10],["ACE_packingBandage",15],["ACE_Clacker",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",5,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["R3F_ITEM_Brouilleur",1],["rhsusf_m112_mag",4,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_24","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Equipier = [[["rhs_weap_hk416d10","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_light",[["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",5,30],["SmokeShell",6,1],["rhs_mag_m67",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ToolKit",1],["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","","TFAR_anprc152_27","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Grenadier = [[["rhs_weap_hk416d145_m320","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],["rhs_mag_M433_HEDP",1],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_grenadier",[["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",10,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15],["rhs_mag_M433_HEDP",15,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_8","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_GV = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],[],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_rifleman",[["ACE_plasmaIV_500",2],["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1]]],[],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_5","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_GvBck = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_rifleman",[["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",10,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_7","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Medecin = [[["rhs_weap_hk416d145","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_medic",[["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_surgicalKit",1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m18_green",1,1],["rhs_mag_m18_purple",1,1],["rhsusf_mag_17Rnd_9x19_JHP",1,17]]],["B_Kitbag_mcamo",[["ACE_splint",8],["ACE_epinephrine",6],["ACE_morphine",6],["ACE_bloodIV",14],["ACE_bloodIV_500",16],["ACE_elasticBandage",20],["ACE_packingBandage",30]]],"rhsusf_opscore_paint","",[],["ItemMap","","TFAR_anprc152_21","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Minimi5 = [[["rhs_weap_m249_light_S","","","rhsusf_acc_g33_xps3",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_machinegunner",[["ACE_EarPlugs",1],["rhsusf_200Rnd_556x45_box",3,200]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15],["rhs_mag_m67",2,1],["SmokeShell",5,1],["rhsusf_200Rnd_556x45_box",1,200],["rhsusf_mag_17Rnd_9x19_JHP",1,17]]],"rhsusf_opscore_mc_cover","",["Laserdesignator","","","",[],[],""],["ItemMap","","TFAR_anprc152_9","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Minimi7 = [[["rhs_weap_m240G","","","rhsusf_acc_elcan_3d",["rhsusf_100Rnd_762x51",100],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_machinegunner",[["ACE_EarPlugs",1],["rhsusf_100Rnd_762x51",4,100]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_elasticBandage",10],["ACE_packingBandage",15],["rhs_mag_m67",2,1],["SmokeShell",5,1],["rhsusf_100Rnd_762x51",2,100]]],"rhsusf_opscore_mc_cover","",["Laserdesignator","","","",[],[],""],["ItemMap","","TFAR_anprc152_10","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_TP = [[["rhs_weap_mk17_LB","","","rhsusf_acc_su230a_c_3d",["rhs_mag_20Rnd_SCAR_762x51_m80_ball",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_CableTie",5],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["rhsusf_plateframe_marksman",[["ACE_EarPlugs",1],["rhs_mag_20Rnd_SCAR_762x51_m80_ball",8,20],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_packingBandage",15],["ACE_elasticBandage",10],["SmokeShell",10,1],["rhs_mag_m67",2,1]]],"rhsusf_opscore_mc_cover","",[],["ItemMap","","TFAR_anprc152_25","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]]; 
DISLoadMc_var_Zeus = [[["rhs_weap_hk416d10","","","rhsusf_acc_g33_xps3",["30Rnd_556x45_Stanag_red",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_CombatUniform_mcam_tshirt",[["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",15]]],["V_Rangemaster_belt",[["ACE_EarPlugs",1],["30Rnd_556x45_Stanag_red",3,30],["rhsusf_mag_17Rnd_9x19_JHP",1,17]]],["TFAR_rt1523g_rhs",[]],"rhsusf_patrolcap_ocp","",[],["ItemMap","","TFAR_anprc152_26","ItemCompass","ItemWatch",""]],[["ace_earplugs",true]]];


DISLoadPL_var_CDG = [
    [
        ["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],
        ["rhs_weap_M136","","","",[],[],""],
        ["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],
        ["U_B_Wetsuit",[["ACE_tourniquet",4],["ACE_CableTie",4],["ACE_elasticBandage",10],["ACE_morphine",5],["ACE_packingBandage",20],["ACE_epinephrine",5],["ACE_splint",6],["ACE_EarPlugs",1],["R3F_ITEM_ODP",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],
        ["V_RebreatherB",[]],
        ["rhssaf_kitbag_smb",[["ACE_plasmaIV_500",4],["SmokeShellGreen",1,1],["30Rnd_556x45_Stanag_red",10,30],["rhs_mag_m67",2,1],["SmokeShell",4,1],["rhsusf_plateframe_light",false]]],
        "rhsusf_opscore_mc",
        "G_B_Diving",
        ["Binocular","","","",[],[],""],
        ["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]
    ],
    [["ACE_EarPlugs",true]]
    ];

DISLoadMc_var_CdG = [
    [
        ["rhs_weap_hk416d145","","","rhsusf_acc_eotech_xps3",["30Rnd_556x45_Stanag_red",30],[],""],
        ["rhs_weap_M136","","","",[],[],""],
        ["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],
        ["rhs_uniform_g3_mc",[["ACE_EarPlugs",1],["ACE_CableTie",10],["ACE_splint",4],["ACE_tourniquet",4],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_packingBandage",20],["ACE_elasticBandage",12]]],["rhsusf_plateframe_teamleader",[["ACE_MapTools",1],["SmokeShellGreen",1,1],["acex_intelitems_notepad",1,1],["30Rnd_556x45_Stanag_red",8,30],["SmokeShell",10,1],["rhs_mag_m67",3,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],
        ["rhsusf_falconii_mc",[["ACE_plasmaIV_500",4],["ACE_EntrenchingTool",1]]],
        "rhsusf_opscore_mc_cover_pelt",
        "",
        ["Laserdesignator","","","",[],[],""],
        ["ItemMap","R3F_ITEM_DAGR","TFAR_anprc152","ItemCompass","ItemWatch",""]
    ],
    [["ACE_EarPlugs",true]]
];
